### ISSUE TITLE
Error: Attempt to change mapping for "wasm" extension from "application/wasm" to "application/wasm". Pass `force=true` to allow this, otherwise remove "wasm" from the list of extensions for "application/wasm".

### ISSUE THREAD

**Issue by john1jan** [webpack/webpack-dev-middleware#289]
```
Error: Attempt to change mapping for "wasm" extension from "application/wasm" to "application/wasm". Pass `force=true` to allow this, otherwise remove "wasm" from the list of extensions for "application/wasm".

at Mime.define (node_modules/webpack-dev-middleware/node_modules/mime/Mime.js:49:15)
at Object.<anonymous> (node_modules/webpack-dev-middleware/lib/middleware.js:8:6)
```

**Comment by shellscape** [comment]
Closing as invalid. Read the issue template.
