### ISSUE TITLE
TypeError: Cannot read property 'invalid' of undefined

### ISSUE THREAD

**Issue by qingyulove** [webpack/webpack-dev-middleware#294]
code : 
var webpackConfig = (process.env.NODE_ENV === 'testing' || process.env.NODE_ENV === 'production')
  ? require('./webpack.prod.conf')
  : require('./webpack.dev.conf')
var compiler = webpack(webpackConfig)

var devMiddleware = require('webpack-dev-middleware')(compiler, {
  publicPath: webpackConfig.output.publicPath,
  quiet: true
})

**error :**

D:\html\mui-vue2-master\mui-vue2-master\node_modules\webpack-dev-middleware\lib\context.js:95
  context.compiler.hooks.invalid.tap('WebpackDevMiddleware', invalid);

TypeError: Cannot read property 'invalid' of undefined
    at ctx (D:\html\mui-vue2-master\mui-vue2-master\node_modules\webpack-dev-middleware\lib\context.js:95:26)
    at wdm (D:\html\mui-vue2-master\mui-vue2-master\node_modules\webpack-dev-middleware\index.js:46:19)
    at Object.<anonymous> (D:\html\mui-vue2-master\mui-vue2-master\build\dev-server.js:88:54)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-meituan@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-meituan@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\liuhx\AppData\Roaming\npm-cache\_logs\2018-04-09T07_24_34_833Z-debug.log

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
