### ISSUE TITLE
[BUG] Compiling fails once the server has started.

### ISSUE THREAD

**Issue by NitroBAY** [webpack/webpack-dev-middleware#314]
* Operating System: Windows 10
* Node Version: 8.11.2
* NPM Version: 5.6.0
* webpack version: 4.16.0
* webpack-dev-middleware Version: 3.1.3

This is a **bug**

### Code

```js
// please provide your webpack.config.js for bug reports
```
webpack.common.babel
```
export default (mode: 'development' | 'production'): webpack.Configuration[] => {
  const resolve = {
    modules: ['node_modules', path.resolve(__dirname)],
    extensions: ['.tsx', '.ts', '.js', '.json', '.ejs', '*'],
  };

  const module = {
    rules: [
      /*{
        test: /\.(jsx?|tsx?)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['babel-preset-env'],
          },
        },
      },*/

      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  };

  console.log(`dir ${__dirname}`);
  return [{
    mode,
    resolve,
    module,
    name: 'client',
    target: 'web',
    entry: ['./source/client/js/index.ts'],
    plugins: [
      new HtmlWebpackPlugin(),
    ],
    output: {
      publicPath: 'distribution',
      filename: 'build.js',
      path: path.resolve(__dirname, `distribution/${mode}/client`),
    },
  }, {
    mode,
    resolve,
    module,
    entry: [`./source/server/${mode}.ts`],
    name: 'server',
    target: 'node',
    node: {
      __dirname: true,
    },
    output: {
      publicPath: 'distribution',
      filename: 'build.js',
      path: path.resolve(__dirname, `distribution/${mode}/server`),
    },
  }];
};

```
webpack.development.babel.ts
```
import arrayMerge from './source/shared/array-webpack-merge';
import common from './webpack.common.babel';
import webpack from 'webpack';
import path from 'path';

const config: webpack.Configuration[] = common('development');

// (<String[]>config.find(c => c.name === 'client').entry).unshift('webpack-hot-middleware/client');

console.log(`dir ${__dirname}`);

export default <webpack.Configuration[]>arrayMerge(config, <webpack.Configuration>{
  devtool: 'inline-source-map',
  // plugins: [new webpack.HotModuleReplacementPlugin()],
});


```
json

package.json
```
{
  "name": "34-ILAN",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "build-dev": "cross-env TS_NODE_PROJECT=\"tsconfig-for-webpack-config.json\" webpack --config webpack.development.babel.ts",
    "build-prod": "cross-env TS_NODE_PROJECT=\"tsconfig-for-webpack-config.json\" webpack --config webpack.production.babel.ts",
    "build-both": "npm run build-dev && npm run build-prod",
    "start": "node distribution/development/server/build.js",
    "start-prod": "node distribution/production/server/build.js"
  },
  "devDependencies": {
    "@types/express": "^4.16.0",
    "@types/html-webpack-plugin": "^2.30.3",
    "@types/node": "^10.5.2",
    "@types/webpack": "^4.4.6",
    "@types/webpack-dev-middleware": "^2.0.2",
    "@types/webpack-hot-middleware": "^2.16.4",
    "@types/webpack-merge": "^4.1.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "babel-register": "^6.26.0",
    "cross-env": "^5.2.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "html-webpack-plugin": "^4.0.0-alpha",
    "install": "^0.12.1",
    "ts-loader": "^4.4.2",
    "ts-node": "^7.0.0",
    "tsconfig-paths": "^3.4.2",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "tslint": "^5.10.0",
    "tslint-config-airbnb": "^5.9.2",
    "typescript": "^2.9.2",
    "typescript-eslint-parser": "^16.0.1",
    "webpack": "^4.16.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3",
    "webpack-server-middleware": "^0.1.0"
  },
  "eslintConfig": {
    "parser": "typescript-eslint-parser",
    "extends": [
      "airbnb"
    ]
  },
  "dependencies": {
    "express": "^4.16.3"
  }
}
```

development.ts

```
import config from 'webpack.development.babel';

function initServer(callback?: Function) {
  const app: express.Application = express();

  if (callback) callback(app);

  app.listen(80, () => {
    console.log('Listening at http://localhost:80');
  });

  /*app.get('/', (req, res) => {
    res.sendFile(path.resolve('distribution/production/client/index.html'));
  });*/

  return app;
}

initServer((app) => {
  console.log('config :');
  console.log(config);
  const compiler = webpack(config);

  app.use(middleware(compiler));
  // NOTE: Only the client bund
  // le needs to be passed to `webpack-hot-middleware`.
  // const compilers: webpack.ICompiler[] = compiler.compilers;
  /*app.use(webpackHotMiddleware(compilers.find((compiler: webpack.Compiler) => (
    compiler.name === 'client'
  ))));*/

  // app.use(webpackServerMiddleware(compiler));
});
```

### Actual Behavior
Webpack compiles when I `npm run build-dev`, the server starts when I `npm start` but then everything fails : 
ERROR in ./source/client/js/index.ts
    Module build failed (from ./node_modules/ts-loader/index.js):
    Error: Cannot find module 'C:\www\eds-www\34-ILAN\node_modules\ts-loader\index.js'
        at C:\www\eds-www\34-ILAN\distribution\development\server\build.js:117932:11
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
     @ multi ./source/client/js/index.ts main[0]

    ERROR in   Error: Child compilation failed:
      Module build failed (from ./node_modules/html-webpack-plugin/lib/loader.js):
      Error: Cannot find module 'C:\www\eds-www\34-ILAN\node_modules\html-webpack-plugin\lib\loader.js'

      - build.js:117932
        C:/www/eds-www/34-ILAN/distribution/development/server/build.js:117932:11

      - Error: Cannot find module 'C:\www\eds-www\34-ILAN\node_modules\html-webpack-plugin\lib\loader.js'
ETC.
And for server it logs 
Child server:
    Hash: 3b4dbbc431375ef40cf0
    Time: 257ms
    Built at: 2018-07-14 22:17:25
       Asset      Size  Chunks             Chunk Names
    build.js  9.23 KiB    main  [emitted]  main
    Entrypoint main = build.js
    [./source/server/development.ts] 348 bytes {main} [built] [failed] [1 error]
    [0] multi ./source/server/development.ts 28 bytes {main} [built]

    ERROR in ./source/server/development.ts
    Module build failed (from ./node_modules/ts-loader/index.js):
    Error: Cannot find module 'C:\www\eds-www\34-ILAN\node_modules\ts-loader\index.js'
        at C:\www\eds-www\34-ILAN\distribution\development\server\build.js:117932:11
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
     @ multi ./source/server/development.ts main[0]

### For Bugs; How can we reproduce the behavior?
...

**Comment by NitroBAY** [comment]
ts-loader and html-webpack-plugin are installed and are present where the system tries in the folder that webpack is looking in.

**Comment by NitroBAY** [comment]
Okay I needed to use `webpack-node-externals`... I've been wondering about this issue for tens of hours and suddenly figure out right after having filling this issue...
