### ISSUE TITLE
Excuse me, how about use this lib in koa.

### ISSUE THREAD

**Issue by zgj233** [webpack/webpack-dev-middleware#341]
my code
```javascript
const koa = require("koa");
const app = new koa();
const config = require(`${__dirname}/webpack.config.js`);
const webpack = require("webpack");
const webpackDevMiddleware = require("webpack-dev-middleware");
const compiler = webpack(config);
app.use(webpackDevMiddleware(compiler,{
  publicPath: config.output.publicPath
})).listen(3000);
```

but throw error
```bash
  TypeError: res.setHeader is not a function
      at handleRangeHeaders (D:\My-personal-project\webpack-study\node_modules\webpack-dev-middleware\lib\util.js:120:9)
      at processRequest (D:\My-personal-project\webpack-study\node_modules\webpack-dev-middleware\lib\middleware.js:70:19)
      at ready (D:\My-personal-project\webpack-study\node_modules\webpack-dev-middleware\lib\util.js:51:12)
      at handleRequest (D:\My-personal-project\webpack-study\node_modules\webpack-dev-middleware\lib\util.js:167:5)
      at Promise (D:\My-personal-project\webpack-study\node_modules\webpack-dev-middleware\lib\middleware.js:40:7)
      at new Promise (<anonymous>)
      at middleware (D:\My-personal-project\webpack-study\node_modules\webpack-dev-middleware\lib\middleware.js:39:12)
      at dispatch (D:\My-personal-project\webpack-study\node_modules\koa-compose\index.js:42:32)
      at D:\My-personal-project\webpack-study\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (D:\My-personal-project\webpack-study\node_modules\koa\lib\application.js:151:12)
      at Server.handleRequest (D:\My-personal-project\webpack-study\node_modules\koa\lib\application.js:133:19)
      at Server.emit (events.js:182:13)
      at parserOnIncoming (_http_server.js:652:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

thanks. 😁

**Comment by michael-ciniawsky** [comment]
[koa-webpack](https://github.com/shellscape/koa-webpack)

**Comment by zgj233** [comment]
thanks
