### ISSUE TITLE
V4 rc: options.json not published to npm. Causes build failure

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack-dev-middleware#588]
@evilebottnawi @sokra we are missing the `options.json` file. It looks like it's not copied over in the build / npm ignored. Blocking me from attempting to upgrade Next.js to Webpack 5 & I don't have push / publish access. Can someone who does re-publish it with its schema file :) 

- Operating System: OSX
- Node Version: 11
- NPM Version: 6
- webpack Version: 5
- webpack-dev-middleware Version: 4.0.0-rc.0

### Expected Behavior
v4 beta should work 

### Actual Behavior
beta does not work because the schema options are missing. 

### Code

```js
{ Error: Cannot find module './options.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Volumes/zack_dev/OSS/next.js/node_modules/webpack-dev-middleware/dist/index.js:22:39)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3) code: 'MODULE_NOT_FOUND' }

```

```js
// additional code, HEY YO remove this block if you don't need it
```
![image](https://user-images.githubusercontent.com/25274700/74918542-131eed00-537e-11ea-92d1-31cdc47a4ba2.png)

**Comment by evilebottnawi** [comment]
WIP

**Comment by ScriptedAlchemy** [comment]
LOL looks like we both were on it 😂

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack/webpack-dev-middleware/releases/tag/v4.0.0-rc.1

**Comment by evilebottnawi** [comment]
Feel free to leave feedback on rc version

**Comment by ScriptedAlchemy** [comment]
Appreciate it Evilebot Ill give it a go tomorrow
