### ISSUE TITLE
Error webpackDevMiddleware is not a function

### ISSUE THREAD

**Issue by jimblue** [webpack/webpack-dev-middleware#652]
### Operating System

- Node Version: v12.17.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- webpack-dev-middleware Version: v4.0.0-rc.1

### Actual Behavior

I have a Webpack config working very well until I update to v4.0.0-rc.1.
To upgrade y code I've followed the deprecation info in the release note.
For the rest my config is very similar to the doc exemple with express.
The only difference is that I use Browsersync instead of express.

Here is the error i get when running my app :

```bash
TypeError: devMiddleware is not a function
    at Object.<anonymous> (/Users/jimblue/Repositories/websites/webpacker/modes/development.js:7:20)
at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at webpacker (/Users/jimblue/Repositories/websites/webpacker/index.js:30:3)
    at Object.<anonymous> (/Users/jimblue/Repositories/websites/webpack.config.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! @ webpacker:dev: `cross-env NODE_ENV=development node webpack.config.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the @ webpacker:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jim/.npm/_logs/2020-06-01T14_24_05_126Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

I've try to simplify my config to the maximum to be sure the error is not caused by something else than Webpack dev middleware. But even with the really simple code bellow I keep getting the same error

### Code

```js
const webpack = require('webpack')
const webpackConfig = require('../webpackconfig')
const devMiddleware = require('webpack-dev-middleware')

const compiler = webpack(webpackConfig)

const middleware = devMiddleware(compiler)

console.log(middleware)
```

**Comment by jimblue** [comment]
I just found that it's maybe because of the export default.
When I was able to require dev middleware like so:
```js
const { default: webpackDevMiddleware } = require('webpack-dev-middleware')
```
Not sure why

**Comment by evilebottnawi** [comment]
Yes, please use `const { default: webpackDevMiddleware } = require('webpack-dev-middleware')`, we need improve changelog about it

**Comment by jimblue** [comment]
That lead me to a new same kind of error :

```js
(node:17607) UnhandledPromiseRejectionWarning: TypeError: res.get is not a function
    at processRequest (/Users/jimblue/Repositories/websites/webpacker/node_modules/webpack-dev-middleware/dist/middleware.js:67:18)
    at ready (/Users/jimblue/Repositories/websites/webpacker/node_modules/webpack-dev-middleware/dist/utils/ready.js:11:12)
    at /Users/jimblue/Repositories/websites/webpacker/node_modules/webpack-dev-middleware/dist/middleware.js:91:26
    at new Promise (<anonymous>)
    at middleware (/Users/jimblue/Repositories/websites/webpacker/node_modules/webpack-dev-middleware/dist/middleware.js:48:12)
    at call (/Users/jimblue/Repositories/websites/webpacker/node_modules/connect/index.js:239:7)
    at next (/Users/jimblue/Repositories/websites/webpacker/node_modules/connect/index.js:183:5)
    at next (/Users/jimblue/Repositories/websites/webpacker/node_modules/connect/index.js:161:14)
    at next (/Users/jimblue/Repositories/websites/webpacker/node_modules/connect/index.js:161:14)
    at respModifierMiddleware (/Users/jimblue/Repositories/websites/webpacker/node_modules/resp-modifier/index.js:73:28)
(node:17607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by jimblue** [comment]
This time I have no idea how could I handle that 😞

**Comment by jimblue** [comment]
> Yes, please use `const { default: webpackDevMiddleware } = require('webpack-dev-middleware')`, we need improve changelog about it

Yes @evilebottnawi, that could potentially prevent someone else to loose few hours 😄

**Comment by evilebottnawi** [comment]
@jimblue Do you use `express`? We support express only officially

**Comment by jimblue** [comment]
I'm using Browsersync :(

**Comment by jimblue** [comment]
It could be nice to also add this info on the doc then @evilebottnawi

**Comment by evilebottnawi** [comment]
@jimblue Can you create reproducible test repo, maybe we can fix compatibility with BrowserSync

**Comment by jimblue** [comment]
Yes sure 😄

**Comment by cruzdanilo** [comment]
i am also having the same error while using `connect` (via `hexo-server`) + `webpack-hot-middleware`

```
connect: 3.7.0
webpack: 5.0.0-beta.17
webpack-dev-middleware: 4.0.0-rc.1
webpack-hot-middleware: 2.25.0

(node:56751) UnhandledPromiseRejectionWarning: TypeError: res.get is not a function
    at processRequest (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/webpack-dev-middleware/dist/middleware.js:67:18)
    at ready (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/webpack-dev-middleware/dist/utils/ready.js:11:12)
    at /Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/webpack-dev-middleware/dist/middleware.js:91:26
    at new Promise (<anonymous>)
    at middleware (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/webpack-dev-middleware/dist/middleware.js:48:12)
    at call (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/connect/index.js:239:7)
    at next (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.error (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/send/index.js:421:12)
    at onstat (/Users/cruzdanilo/Documents/cruzdanilo/cruzdanilo.com/node_modules/send/index.js:726:26)
    at FSReqCallback.oncomplete (fs.js:175:21)
```

**Comment by evilebottnawi** [comment]
@cruzdanilo please don't spam - create reproducible test repo

**Comment by cruzdanilo** [comment]
spam?

**Comment by evilebottnawi** [comment]
@cruzdanilo we know that we have this problem, we don’t need to show the error stack again, better create a test repo and we fix it

**Comment by jimblue** [comment]
I didn't forgot about a testing repo @evilebottnawi , just don't had the time yet.
Maybe be this weekend 🤞

**Comment by jimblue** [comment]
I've finally move to express using `webpack-dev-server` because of performance problem with `BrowserSync`.
