### ISSUE TITLE
'indexOf' of undefined on url.indexOf(localPrefix)

### ISSUE THREAD

**Issue by zckrs** [webpack/webpack-dev-middleware#82]
Hi,

I just update to v1.6.0 and a error occurred  

```
TypeError: Cannot read property 'indexOf' of undefined
   at getFilenameFromUrl (/home/zckrs/project/node_modules/webpack-dev-middleware/middleware.js:129:9)
   at webpackDevMiddleware (/home/zckrs/project/node_modules/webpack-dev-middleware/middleware.js:174:18)
   at call (/home/zckrs/project/node_modules/connect/index.js:239:7)
   at next (/home/zckrs/project/node_modules/connect/index.js:183:5)
...
...
```

**Comment by zhengcan** [comment]
+1

**Comment by tomgrooffer** [comment]
+1

**Comment by domark0721** [comment]
+1

**Comment by franklinkim** [comment]
+1

**Comment by ianwcarlson** [comment]
+1

**Comment by maxlapides** [comment]
This is a duplicate of #79

**Comment by jhnns** [comment]
I've reverted the broken commit. I don't know why @sokra has merged it in the first place. Its purpose is unclear to me.

 I'll try to publish this asap (don't have the rights to publish it on npm :disappointed:).
