### ISSUE TITLE
Invalid argument in watchOptions

### ISSUE THREAD

**Issue by name-k** [webpack/webpack-dev-middleware#86]
I'm getting this error
```
D:\my-path\node_modules\webpack-dev-middleware\middleware.js:107
                        if(err) throw err;
                                ^
 Error: invalid argument
    at pathToArray (D:\my-path\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (D:\my-path\node_modules\memory-fs\lib\MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (D:\my-path\node_modules\memory-fs\lib\MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (D:\my-path\node_modules\webpack\lib\Compiler.js:229:25)
    at Compiler.applyPluginsAsync (D:\my-path\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.emitAssets (D:\my-path\node_modules\webpack\lib\Compiler.js:226:7)
    at Watching.<anonymous> (D:\my-path\node_modules\webpack\lib\Compiler.js:54:18)
    at D:\my-path\node_modules\webpack\lib\Compiler.js:403:12
    at Compiler.next (D:\my-path\node_modules\tapable\lib\Tapable.js:67:11)
    at Compiler.<anonymous> (D:\my-path\node_modules\webpack\lib\CachePlugin.js:40:4)
```

This is the code that throws an error:
```
	if(!options.lazy) {
		var watching = compiler.watch(options.watchOptions, function(err) {
			if(err) throw err;
		});
	} else {
		state = true;
	}
```

Error object:
```
{ [Error: invalid argument]
  code: 'EINVAL',
  errno: 18,
  message: 'invalid argument',
  path: 'build\\js' }
```

Watch options I'm passing:
```
watchOptions: {
        aggregateTimeout: 100
    }
```

if there is ```lazy : true``` option - everything works fine

**Comment by name-k** [comment]
The problem was in output path in webpacks config, it should be absolute after all.
