### ISSUE TITLE
prefetch failed with webpack 5 + webpack dev middleware

### ISSUE THREAD

**Issue by srigar** [webpack/webpack-dev-middleware#936]
- Operating System: Mac 10.14.6
- Node Version: 12.18.4
- NPM Version: 6.14.6
- webpack Version: webpack 5.38.2
- webpack-dev-middleware Version: 5.0.0

### Expected Behavior

Server should get start without any error with **webpackPrefetch** in dynamic import

### Actual Behavior

Got below error while starting server with webpack-dev-middleware

/Users/Documents/dev/product/build/server.js:21367
/******/                __webpack_require__.O(0, ["server"], () => (), 5);
                                                                    ^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

### Code

Issue is because of adding **webpackPrefetch** in below import  and it is working fine without that.

```js
import loadable from '@loadable/component';

const Component = loadable(
    () =>
        import(
            /* webpackPrefetch: true */ /* webpackChunkName: "compChunk" */ '../component'
        ),
    { ssr: false }
);
```

**Comment by srigar** [comment]
seems its an issue with webpack 5 I guess. Let me close it for now
