### ISSUE TITLE
can't use in typescript

### ISSUE THREAD

**Issue by ioriandy4** [webpack/webpack-dev-middleware#986]
When the typescript file has eslint error ,the webpack-dev-server will crash. I use ts-loader to handle .ts file

First i write the normal code and run the project
```js
// main.ts
console.l og('aaa');
```
Then i change the code so it has eslint error

```js
// main.ts
console.l   og('aaa');
```

The webpack-dev-server will crash

```
Local: http://localhost:9001
<e> [webpack-dev-middleware] Error: The loaded module contains errors
<e>     at D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\dependencies\LoaderPlugin.js:110:11
<e>     at D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\Compilation.js:1674:8
<e>     at D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\util\AsyncQueue.js:352:5
<e>     at Hook.eval [as callAsync] (eval at create (D:\code\my\test\created-cli-demo\444\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
<e>     at AsyncQueue._handleResult (D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\util\AsyncQueue.js:322:21)
<e>     at D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\util\AsyncQueue.js:305:11
<e>     at D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\Compilation.js:1346:15
<e>     at D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\HookWebpackError.js:68:3
<e>     at Hook.eval [as callAsync] (eval at create (D:\code\my\test\created-cli-demo\444\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
<e>     at Cache.store (D:\code\my\test\created-cli-demo\444\node_modules\webpack\lib\Cache.js:107:20)
```

**Comment by alexander-akait** [comment]
Please open an issue in ts-loader
